// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGmegh9r1obKvyA00ZNbN-2RWp9KDCUg',
    appId: '1:958782462924:web:4dcfba3170c64aae501b69',
    messagingSenderId: '958782462924',
    projectId: 'sidoktan-48bfd',
    authDomain: 'sidoktan-48bfd.firebaseapp.com',
    storageBucket: 'sidoktan-48bfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGSqviAWBvRubTEJ9heYZa4UQ2trjVdk',
    appId: '1:958782462924:android:2cf4c5428659b911501b69',
    messagingSenderId: '958782462924',
    projectId: 'sidoktan-48bfd',
    storageBucket: 'sidoktan-48bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRZvrulxzCKzqsFvWjOBlFPqOnIeX4tI',
    appId: '1:958782462924:ios:ab24ab22f391d762501b69',
    messagingSenderId: '958782462924',
    projectId: 'sidoktan-48bfd',
    storageBucket: 'sidoktan-48bfd.appspot.com',
    iosBundleId: 'com.example.sidoktan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRZvrulxzCKzqsFvWjOBlFPqOnIeX4tI',
    appId: '1:958782462924:ios:ab24ab22f391d762501b69',
    messagingSenderId: '958782462924',
    projectId: 'sidoktan-48bfd',
    storageBucket: 'sidoktan-48bfd.appspot.com',
    iosBundleId: 'com.example.sidoktan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMGmegh9r1obKvyA00ZNbN-2RWp9KDCUg',
    appId: '1:958782462924:web:93373ebc36e446a5501b69',
    messagingSenderId: '958782462924',
    projectId: 'sidoktan-48bfd',
    authDomain: 'sidoktan-48bfd.firebaseapp.com',
    storageBucket: 'sidoktan-48bfd.appspot.com',
  );
}
